### ISSUE TITLE
User gets 500 Internal Server Error on Clicking getting started button on pytesthistoric portal

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-historic#2]
Steps to reproduce:
1. Open Power shell / command prompt
2. Run pytesthistoric command
3. Open localhost:5000 on browser
4. Click on Getting Started Button

**Issue** : User gets Internal Server Error (500). Refer Screenshot below:

![image](https://user-images.githubusercontent.com/12759282/76233040-9466f280-624d-11ea-968e-446e48f51086.png)

**Console Logs :**

**PS C:\Users\Rahul> pytesthistoric**

 * Serving Flask app "pytest_historic.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [09/Mar/2020 21:29:31] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [09/Mar/2020 21:29:45] "[37mGET / HTTP/1.1[0m" 200 -
[2020-03-09 21:29:56,499] ERROR in app: Exception on /home [GET]
Traceback (most recent call last):
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytest_historic-0.1.0-py3.7.egg\pytest_historic\app.py", line 20, in home
    cursor = mysql.connection.cursor()
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_mysqldb-0.2.0-py3.7.egg\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_mysqldb-0.2.0-py3.7.egg\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\MySQLdb\__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\MySQLdb\connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2059, "Authentication plugin 'caching_sha2_password' cannot be loaded: The specified module could not be found.\r\n")

**Comment by adiralashiva8** [comment]
Seems need to modify code while launching app

Work Around: Install `pip install MySQL-connector-python`

Reference: https://stackoverflow.com/questions/50557234/authentication-plugin-caching-sha2-password-is-not-supported

**Comment by parwalrahul** [comment]
Shiva - This does not help but it is something related to the installation. I tried multiple steps but none worked. 
Creating one documentation bug with suggested step to do while installing to avoid this issue.
