### ISSUE TITLE
Getting error logs on console after test execution while using pytesthistoric

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-historic#6]
**Console Logs :**

![image](https://user-images.githubusercontent.com/12759282/76333461-b0cf6180-6317-11ea-9c50-ffe97b60178f.png)

Exception ignored in: <function BaseMySQLSocket.__del__ at 0x03A2EDB0>
Traceback (most recent call last):
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\mysql\connector\network.py", line 149, in __del__
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\mysql\connector\network.py", line 137, in shutdown
TypeError: catching classes that do not inherit from BaseException is not allowed
Exception ignored in: <function BaseMySQLSocket.__del__ at 0x03A2EDB0>
Traceback (most recent call last):
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\mysql\connector\network.py", line 149, in __del__
  File "C:\Users\Rahul\AppData\Local\Programs\Python\Python37-32\lib\site-packages\mysql\connector\network.py", line 137, in shutdown
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by adiralashiva8** [comment]
Above stacktrace doesnt conist of rfhistoric or hook related info, Could you please share full stacktrace so I can debug at my end

**Comment by parwalrahul** [comment]
This is the only log that we get after execution. Not sure if this is some issue with MySQL 8.0.
